/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package com.Gooey.jugadores;

import static com.Gooey.jugadores.Jugadores.agregarJugador;
import static com.Gooey.jugadores.Jugadores.eliminarJugador;
import static com.Gooey.jugadores.Jugadores.listarJugadores;
import static com.Gooey.jugadores.Jugadores.mostrarJugador;
import java.io.*;
import java.io.FileReader;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author Windows
 */
public class FrmGui1 extends javax.swing.JFrame {
    public FrmGui1() {
    initComponents();
        int LineCnt = 0;
        int i = 0;
        String [] usuario = null;
        String linea;
        String[] usuarios = new String[LineCnt];

    
            
    /**
     *
     * @param args
     */
    //public static void main(String[] args) {
    
    /**
     * Creates new form frmGui1
     */
        //public FrmGui1() {
       // initComponents();
        //JFrame frame = new JFrame("Crud");
         //frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        IDLbl = new javax.swing.JLabel();
        UsrLbl = new javax.swing.JLabel();
        LvlLbl = new javax.swing.JLabel();
        ScoreLbl = new javax.swing.JLabel();
        IDTxt = new javax.swing.JTextField();
        UsrTxt = new javax.swing.JTextField();
        LvlChar = new javax.swing.JTextField();
        ScoreTxt = new javax.swing.JTextField();
        EditBtn = new javax.swing.JButton();
        FindBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        IDLbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        IDLbl.setText("ID");

        UsrLbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        UsrLbl.setText("username");

        LvlLbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        LvlLbl.setText("nivel");

        ScoreLbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        ScoreLbl.setText("score");

        IDTxt.setToolTipText("ingrese id");
        IDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTxtActionPerformed(evt);
            }
        });

        UsrTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsrTxtActionPerformed(evt);
            }
        });

        LvlChar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LvlCharActionPerformed(evt);
            }
        });

        ScoreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScoreTxtActionPerformed(evt);
            }
        });

        EditBtn.setText("Editar");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });

        FindBtn.setText("Buscar");
        FindBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindBtnActionPerformed(evt);
            }
        });

        SaveBtn.setText("Guardar");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setText("Eliminar");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("POJito");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(136, 136, 136)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LvlChar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(UsrTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                                .addComponent(ScoreTxt)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(IDLbl)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                            .addComponent(IDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(FindBtn))
                                        .addComponent(UsrLbl)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ScoreLbl)
                                        .addComponent(LvlLbl))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(EditBtn)
                        .addGap(18, 18, 18)
                        .addComponent(SaveBtn)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FindBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsrLbl)
                    .addComponent(UsrTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LvlLbl)
                    .addComponent(LvlChar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ScoreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScoreLbl))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void LvlCharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LvlCharActionPerformed
      Scanner sc = new Scanner(System.in);  
     char lvl = sc.next().charAt(0);

    }//GEN-LAST:event_LvlCharActionPerformed

    private void ScoreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScoreTxtActionPerformed
        Scanner sc = new Scanner(System.in);
        String Score = sc.next();
    }
    private void IDTxtActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Scanner sc = new Scanner(System.in);
        String ID = sc.next();
    }
    private void UsrTxtActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Scanner sc = new Scanner(System.in);
        String usrTxt = sc.next();

    }//GEN-LAST:event_ScoreTxtActionPerformed

    //buttons
    
    
    private void FindBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindBtnActionPerformed
        
        int id = Integer.parseInt(IDTxt.getText());
        mostrarJugador(id);

    }//GEN-LAST:event_FindBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        String Usr = this.UsrTxt.getText();
        char lvl = this.LvlChar.getText().charAt(0);
        agregarJugador();
        int id = Integer.parseInt(IDTxt.getText());
        mostrarJugador(id);
        listarJugadores();
        jTextArea1.setText("Se ha guardado al Jugador: " + Usr
                   + " id: " + id);
            
                
                
                

         try {
            Scanner sc = new Scanner(new File("/Users/sergiodeluquez/Downloads/CRUD/gamers-master/src/main/java/com/Gooey/jugadores"));
            File f = new File("/Users/sergiodeluquez/Downloads/CRUD/gamers-master/src/main/java/com/Gooey/jugadores");
            FileReader fr = new FileReader(f);
            BufferedReader br = new BufferedReader(fr);       
            try {
                String linea = null;
                int LineCnt = 0;
                linea = br.readLine();
                while (linea !=  null) {
                LineCnt++;
                }
        } catch (IOException ex) {
            Logger.getLogger(FrmGui1.class.getName()).log(Level.SEVERE, null, ex);
        }

        jTextArea1.setText("Se ha guardado al Jugador: " + UsrTxt.getText()
                    + " id: " + IDTxt.getText());
    ;
    } catch (FileNotFoundException ex) {
        Logger.getLogger(FrmGui1.class.getName()).log(Level.SEVERE, null, ex);
    }
         int LineCnt = 0;
         int i = 0;
                String[] usuarios = new String[LineCnt];
                Scanner sc = new Scanner(System.in);
                while(sc.hasNextLine()){
                usuarios[i++] = sc.nextLine();
                }
                

    }//GEN-LAST:event_SaveBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        int id = Integer.parseInt(IDTxt.getText());
        eliminarJugador(id);
        //usuarios.remove(id);
        jTextArea1.setText("Se ha eliminado al Jugador con id: " + id);
       
// TODO add your handling code here:
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
       agregarJugador();
       jTextArea1.setText("El Jugador ha sido editado: " + UsrTxt.getText()
                        + " id: " + IDTxt.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_EditBtnActionPerformed
/*
    private void UsrTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsrTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsrTxtActionPerformed

    private void IDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTxtActionPerformed

    }//GEN-LAST:event_IDTxtActionPerformed
*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JButton FindBtn;
    private javax.swing.JLabel IDLbl;
    private javax.swing.JTextField IDTxt;
    private javax.swing.JTextField LvlChar;
    private javax.swing.JLabel LvlLbl;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel ScoreLbl;
    private javax.swing.JTextField ScoreTxt;
    private javax.swing.JLabel UsrLbl;
    private javax.swing.JTextField UsrTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
